### ISSUE TITLE
Could not connect on linux server

### ISSUE THREAD

**Issue by Flydexo** [discordjs/RPC#107]
I have uploaded all my project files expect the node_modules to a linux vps. I launch the npm install all is ok but when the rpc tries to connect it gives me an error with the ipc 

```
(node:11202) UnhandledPromiseRejectionWarning: Error: Could not connect
    at Socket.onerror (/var/www/html/redset-rpc/node_modules/discord-rpc/src/transports/ipc.js:32:16)
    at Object.onceWrapper (events.js:286:20)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:11202) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11202) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

 So why is this producing this error ? Thx

**Comment by Flydexo** [comment]
This is a debian server

**Comment by Vaporox** [comment]
The RPC client needs to be run on the same PC where Discord is running, you can't do that on a VPS

**Comment by Flydexo** [comment]
So how i create a public rpc for a tool ?

**Comment by tipakA** [comment]
Have it running on the user's PC.  
Same way how VSCode RPC is in form of an extension that user installs locally.
