### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by EduApps-CDG** [discordjs/RPC#155]
Tried to connect via `ipc` with a client secret and a client id.
```
(node:219724) UnhandledPromiseRejectionWarning: Error: OAuth2 Authorization Error: Unknown Error
    at RPCClient._onRpcMessage (/home/eduardo/games/Xposed/desktop/node_modules/discord-rpc/src/client.js:178:19)
    at IPCTransport.emit (node:events:394:28)
    at /home/eduardo/games/Xposed/desktop/node_modules/discord-rpc/src/transports/ipc.js:138:18
    at decode (/home/eduardo/games/Xposed/desktop/node_modules/discord-rpc/src/transports/ipc.js:92:5)
    at Socket.<anonymous> (/home/eduardo/games/Xposed/desktop/node_modules/discord-rpc/src/transports/ipc.js:120:7)
    at Socket.emit (node:events:394:28)
    at emitReadable_ (node:internal/streams/readable:573:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
```
Any idea of what could this be?

**Comment by Hacksore** [comment]
@EduApps-CDG Are you able to share a small code example?

**Comment by RizkiP4BYT** [comment]
> @EduApps-CDG Are you able to share a small code example?

I have a same issue. This is my code:
```
const RPC = require("discord-rpc");
const clientId = "id";
const clientSecret = "secret"
const scopes = ['rpc', 'rpc.api', 'messages.read'];
const client = new RPC.Client({ transport: 'ipc' });
const startTimestamp= new Date();

client.on('ready', () => {
    client.setActivity({
        details: "Beta RPC",
        state: 'using Visual Studio Code',
        startTimestamp,
        largeImageKey: 'main',
    })
});

client.login({ clientId, scopes, clientSecret});
```

Error output:
```
Error: OAuth2 Authorization Error: Unknown Error
    at RPCClient._onRpcMessage (D:\Code\Experimental Folder\node_modules\←[4mdiscord-rpc←[24m\src\client.js:178:19)
←[90m    at IPCTransport.emit (node:events:394:28)←[39m
    at D:\Code\Experimental Folder\node_modules\←[4mdiscord-rpc←[24m\src\transports\ipc.js:138:18
    at decode (D:\Code\Experimental Folder\node_modules\←[4mdiscord-rpc←[24m\src\transports\ipc.js:92:5)
    at Socket.<anonymous> (D:\Code\Experimental Folder\node_modules\←[4mdiscord-rpc←[24m\src\transports\ipc.js:120:7)
←[90m    at Socket.emit (node:events:394:28)←[39m
←[90m    at emitReadable_ (node:internal/streams/readable:571:12)←[39m
←[90m    at processTicksAndRejections (node:internal/process/task_queues:82:21)←[39m {
  code: ←[33m5000←[39m,
  data: { code: ←[33m5000←[39m, message: ←[32m'OAuth2 Authorization Error: Unknown Error'←[39m }
}
```

**Comment by EduApps-CDG** [comment]
I solved the problem, It happens when you insert `clientSecret` on a IPC login.

**Comment by EduApps-CDG** [comment]
Is there a way to just ignore `clientSecret` like others libs do when you insert invalid data in an `option:object`?
