### ISSUE TITLE
Spread Operator - Unexpected Token SyntaxError

### ISSUE THREAD

**Issue by ElBuenAnvita** [discordjs/RPC#79]
When I execute `npm start`, discord-rpc throws this error:
```
App threw an error during load
C:\Users\CORE I3\Downloads\CR-APP\node_modules\discord-rpc\src\client.js:637
        ...r,
        ^^^

SyntaxError: Unexpected token ...
    at Object.runInThisContext (vm.js:116:10)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\CORE I3\Downloads\CR-APP\node_modules\discord-rpc\src\index.js:6:11)
```
I've found this issue here too: https://github.com/discordjs/RPC/issues/74
And the solve is to "upgranding my tooling", but I need exactly what to upgrade. I had already moved to the newest version of NodeJS and NPM, but that didn't solved that, so I returned to `8.17.0` version of NodeJS (and `6.13.4` of NPM) and I'm there right now.

And there was a time that `discord-rich-presence` package solved that error, but now it keeps throwing this error (on their node_modules) using it or using discord-rpc.

I know that this doesn't happen on 3.0.1 version of discord-rpc. But npm started now installing 3.1.0 even if `package.json` specify the "3.0.1" version. Please tell me if i'm doing something wrong or how do I tell npm to not upgrade to 3.1.0, excuse me if I skipped some info about this too.

**Comment by devsnek** [comment]
All active lines of node.js support spread literals. Please see here for active releases of node: https://nodejs.org/en/about/releases/

**Comment by ElBuenAnvita** [comment]
> 
> 
> All active lines of node.js support spread literals. Please see here for active releases of node: https://nodejs.org/en/about/releases/

Using v12.16.2 of NodeJS keeps throwing error.
```
PS C:\Users\CORE I3\Downloads\CR-APP> npm start
> crunchyrp@1.3.0 start C:\Users\CORE I3\Downloads\CR-APP
> electron .


App threw an error during load
C:\Users\CORE I3\Downloads\CR-APP\node_modules\discord-rpc\src\client.js:637
        ...r,
        ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\CORE I3\Downloads\CR-APP\node_modules\discord-rpc\src\index.js:6:11)
¿Desea terminar el trabajo por lotes (S/N)? S
PS C:\Users\CORE I3\Downloads\CR-APP> node -v
v12.16.2
```

**Comment by devsnek** [comment]
@ElBuenAnvita you're running electron, which bundles its own version of node. make sure you update your version of electron.
