### ISSUE TITLE
"Unexpected token ..." on linux

### ISSUE THREAD

**Issue by mihabozic123** [discordjs/RPC#83]
im getting this error:
```
/home/miha/Desktop/EasyRPC/node_modules/discord-rpc/src/client.js:637
        ...r,
        ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/miha/Desktop/EasyRPC/node_modules/discord-rpc/src/index.js:6:11)

```

**Comment by mihabozic123** [comment]
old node version

**Comment by mihabozic123** [comment]
old node version didn't seem to be the issue :/

**Comment by devsnek** [comment]
old node version is the issue.

**Comment by mihabozic123** [comment]
it is not
i updated it and deleted the old version
problem persists

**Comment by tipakA** [comment]
And the new node version you installed is...?

**Comment by mihabozic123** [comment]
12.18.2

**Comment by advaith1** [comment]
Update to the latest version of SimplePresence (formerly EasyRPC), the electron version was updated to fix this in https://github.com/julianschiavo/SimplePresence/commit/ab8479a3bd0963f04438cb4f49fe2fb3048b3e44
