### ISSUE TITLE
Error "Connection Closed"

### ISSUE THREAD

**Issue by amitojsingh366** [discordjs/RPC#92]
Whenever I try running the example or any other project with 'discord-rpc', I get the following error:
```
Error: connection closed
    at IPCTransport.<anonymous> (E:\Projects\Tests\Rich-Presence-Template-master\node_modules\discord-rpc\src\client.js:118:16) 
    at Object.onceWrapper (events.js:422:26)
    at IPCTransport.emit (events.js:315:20)
    at E:\Projects\Tests\Rich-Presence-Template-master\node_modules\discord-rpc\src\transports\ipc.js:137:18
    at decode (E:\Projects\Tests\Rich-Presence-Template-master\node_modules\discord-rpc\src\transports\ipc.js:92:5)
    at Socket.<anonymous> (E:\Projects\Tests\Rich-Presence-Template-master\node_modules\discord-rpc\src\transports\ipc.js:120:7)
    at Socket.emit (events.js:315:20)
    at emitReadable_ (_stream_readable.js:555:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
```

**Comment by devsnek** [comment]
You most likely do not have permission for the scopes you requested.

**Comment by amitojsingh366** [comment]
Wait I tried the example also same error, How can I fix this??

**Comment by ynhhoJ** [comment]
@devsnek i have the same problem.
