### ISSUE TITLE
Error: connection closed

### ISSUE THREAD

**Issue by TheClashFruit** [discordjs/RPC#96]
```
Error: connection closed
    at IPCTransport.<anonymous> (E:\ThatCakeID\zz\node_modules\discord-rpc\src\client.js:118:16)
    at Object.onceWrapper (events.js:417:26)
    at IPCTransport.emit (events.js:310:20)
    at E:\ThatCakeID\zz\node_modules\discord-rpc\src\transports\ipc.js:137:18
    at decode (E:\ThatCakeID\zz\node_modules\discord-rpc\src\transports\ipc.js:92:5)
    at Socket.<anonymous> (E:\ThatCakeID\zz\node_modules\discord-rpc\src\transports\ipc.js:120:7)
    at Socket.emit (events.js:310:20)
    at emitReadable_ (_stream_readable.js:543:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
```

**Comment by devsnek** [comment]
Most likely you are using scopes you don't have permission to use.

**Comment by TheClashFruit** [comment]
My Code: (There is no scopes)
```js
const clientID = '';

DiscordRPC.register(clientID);

const rpc = new DiscordRPC.Client({ transport: 'ipc' });

const startTimestamp = new Date();

const endTimestamp = startTimestamp + 1000;

function setStatus() {
  rpc.updatePresence({
    state: 'Status',
    details: 'Something',
    startTimestamp,
    endTimestamp,
    largeImageKey: 'icon',
    instance: true
  });
}

rpc.on('ready', () => {
  setStatus();
});

rpc.login({ clientID }).catch(console.error);
```

**Comment by Fyko** [comment]
My guess is you're not authorized to use the IPC transport as it's invite-only.

**The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.**

**Comment by ScottyFillups** [comment]
Shouldn't you be using `setActivity`? I don't tihnk `updatePresence` is a function: https://github.com/discordjs/RPC/blob/master/src/client.js#L480

Also, isn't IPC transport accessible to anyone? I thought only websocket is invite-only.
