### ISSUE TITLE
Error: connection closed

### ISSUE THREAD

**Issue by riiz0r** [discordjs/RPC#98]
Hello,
I am making an RPC client, and it doesn't seem to work. I have everything seemingly correct, but I do not know. My code for the RPC part is:
```js
const DiscordRPC = require("discord-rpc");
const clientID = "773190210455994398";
const rpc = new DiscordRPC.Client({ transport: 'ipc' })
const startTimestamp = new Date()

async function setActivity() {
      rpc.setActivity({
          details: "Details",
          state: "Testing",
          startTimestamp,
          instance: false,
      });
}

rpc.on('ready', () => {
  setActivity();


  setInterval(() => {
    setActivity;
}, 15e3);
});

rpc.login({ clientID }).catch(console.error)
```

**Comment by riiz0r** [comment]
Full error:
`Error: connection closed
    at IPCTransport.<anonymous> (C:\Users\Adn\Documents\rpcclient\node_modules\discord-rpc\src\client.js:118:16)
    at Object.onceWrapper (events.js:313:26)
    at IPCTransport.emit (events.js:223:5)
    at C:\Users\Adn\Documents\rpcclient\node_modules\discord-rpc\src\transports\ipc.js:137:18
    at decode (C:\Users\Adn\Documents\rpcclient\node_modules\discord-rpc\src\transports\ipc.js:92:5)
    at Socket.<anonymous> (C:\Users\Adn\Documents\rpcclient\node_modules\discord-rpc\src\transports\ipc.js:120:7)
    at Socket.emit (events.js:223:5)
    at emitReadable_ (_stream_readable.js:576:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)`

**Comment by riiz0r** [comment]
Never mind, I actually forgot to put the client secret, and my rich presence works now.
